# expose kongo services:
apiVersion: v1
kind: Service
metadata:
  name: kongo-proxy
spec:
  type: NodePort
  ports:
  - name: kongo-proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kongo-proxy-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    # app should mach with deployment: spec.template.labels
    app: kongo
# items separator
---
apiVersion: v1
kind: Service
metadata:
  name: kongo-admin
spec:
  type: NodePort
  ports:
  - name: kongo-proxy
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kongo-proxy-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    # app should mach with deployment: spec.template.labels
    app: kongo
